# Generated by Django 5.0.1 on 2024-08-23 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_endereco_produto_vendedor_remove_cliente_cidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="id_cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="id_produto",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="id_vendedor",
        ),
        migrations.DeleteModel(
            name="Endereco",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Produto",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="Vendedor",
        ),
    ]
