# Generated by Django 5.0.1 on 2024-10-17 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("endereco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("time", models.CharField(default="", max_length=15)),
                ("audiovisual", models.CharField(default="", max_length=20)),
                ("naturalidade_cidade", models.CharField(default="", max_length=30)),
                ("naturalidade_estado", models.CharField(default="", max_length=30)),
                ("nome_formatado", models.CharField(editable=False, max_length=255)),
                (
                    "naturalidade_cidade_formatado",
                    models.CharField(default="", editable=False, max_length=30),
                ),
                (
                    "naturalidade_estado_formatado",
                    models.CharField(default="", editable=False, max_length=30),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="endereco.endereco",
                    ),
                ),
            ],
        ),
    ]
