# Generated by Django 5.0.1 on 2024-10-02 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cliente", "0007_rename_naturalidade_cliente_naturalidade_cidade_and_more"),
        ("produto", "0006_produto_local_de_fabricacao"),
        ("vendedor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id_venda",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("valor_prod", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "id_produto",
                    models.ManyToManyField(
                        related_name="pedidos", to="produto.produto"
                    ),
                ),
                (
                    "id_vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendedor.vendedor",
                    ),
                ),
            ],
        ),
    ]
